### ISSUE TITLE
Uncaught TypeError: implode

### ISSUE THREAD

**Issue by federico-galli** [YOURLS/YOURLS#2871]
Hi, while trying to upgrade from an old 1.7.1 install I got a blank page on admin, 500 error.
With a new install, new config, new db I always get 

`2021/03/15 15:25:41 [error] 11#11: *121 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /application/sclzoo.it/includes/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
Stack trace:
#0 /application/sclzoo.it/includes/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php(195): implode()
#1 /application/sclzoo.it/includes/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_fsockopen->request()
#2 /application/sclzoo.it/includes/functions-http.php(218): Requests::request()
#3 /application/sclzoo.it/includes/functions-http.php(52): yourls_http_request()
#4 /application/sclzoo.it/includes/functions-http.php(324): yourls_http_post()
#5 /application/sclzoo.it/includes/functions-http.php(418): yourls_check_core_version()
#6 /application/sclzoo.it/includes/functions.php(1213): yourls_maybe_check_core_version()
#7 /application/sclzoo.it/includes/Config/Init.php(114): yourls_tell_if_new_version()
#8 /application/sclzoo.it/includ" while reading response header from upstream, client: 172.16.8.6, server: sclzoo.it, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "sclzoo.it"
2021/03/15 15:35:04 [error] 11#11: *123 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /application/sclzoo.it/includes/vendor/rmccue/requests/library/Requests/Transport/fsockopen.php:195
`

and a blank page. 
PhpFpm 8.0 - nginx 
Please help

**Comment by ozh** [comment]
While it *should* work without it, it seems to indicate that you don't have support for curl. Can you enable curl in your php.ini ?

**Comment by ozh** [comment]
Also, does "PhpFpm 8.0" mean you're running PHP 8 ?
